server:
  port: 8081
  error:
    include-stacktrace: never
    include-message: never

spring:
  application:
    name: user-service
  mongodb:
    uri: ${MONGO_URI_USERS}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
