server:
  port: 8081
  error:
    include-stacktrace: never
    include-message: never

spring:
  application:
    name: user-service
  mongodb:
    uri: ${MONGO_URI_USERS:mongodb://localhost:27017/buy01_users}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:dev-local-secret-change-me}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
