server:
  port: 8081

spring:
  application:
    name: user-service
  mongodb:
    uri: mongodb://admin:adminpass@localhost:27017/buy01_users?authSource=admin
  data:
    mongodb:
      spring.mongodb.database: buy01_users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: "this-is-a-long-random-string-at-least-32-bytes-for-hs256"
  expiration-ms: 3600000