services:
  mongo:
    image: mongo:7
    container_name: buy01-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - buy01-network

  discovery:
    build:
      context: ./backend/discovery
    container_name: buy01-discovery
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - buy01-network

  user-service:
    build:
      context: ./backend/user-service
    container_name: buy01-user-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      EUREKA_URI: ${EUREKA_URI}
      MONGO_URI_USERS: ${MONGO_URI_USERS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
    networks:
      - buy01-network
    depends_on:
      - mongo
      - discovery

  product-service:
    build:
      context: ./backend/product-service
    container_name: buy01-product-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      EUREKA_URI: ${EUREKA_URI}
      MONGO_URI_PRODUCTS: ${MONGO_URI_PRODUCTS}
    networks:
      - buy01-network
    depends_on:
      - mongo
      - discovery

  media-service:
    build:
      context: ./backend/media-service
    container_name: buy01-media-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      EUREKA_URI: ${EUREKA_URI}
      MONGO_URI_MEDIA: ${MONGO_URI_MEDIA}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    networks:
      - buy01-network
    depends_on:
      - mongo
      - discovery

  gateway:
    build:
      context: ./backend/gateway
    container_name: buy01-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      EUREKA_URI: ${EUREKA_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      SSL_KEYSTORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}
    networks:
      - buy01-network
    depends_on:
      - discovery

  frontend:
    build:
      context: ./frontend
    container_name: buy01-frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    networks:
      - buy01-network
    depends_on:
      - gateway

networks:
  buy01-network:
    driver: bridge

volumes:
  mongo_data:
