server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: never

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=2

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**
              filters:
                - StripPrefix=2

            - id: media-service
              uri: lb://media-service
              predicates:
                - Path=/api/media/**
              filters:
                - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always