server:
  port: 8083

  error:
    include-stacktrace: never
    include-message: never

spring:
  application:
    name: media-service
  mongodb:
      uri: ${MONGO_URI_MEDIA:mongodb://localhost:27017/buy01_media}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:demo}
  api-key: ${CLOUDINARY_API_KEY:demo}
  api-secret: ${CLOUDINARY_API_SECRET:demo}


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always